version: '3.3'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  nginx:
    image: wanyay/nginx:latest
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    ports:
      - "8010:80"
    networks:
      backend:
        aliases:
          - ${APP_HOST}
  php-fpm:
    image: wanyay/laravel-php:latest
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    networks:
      - backend
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=perfect
      - MYSQL_USER=perfect
      - MYSQL_PASSWORD=perfect
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ~/.docker/perfect/:/var/lib/mysql
    networks:
      - backend
    ports:
      - "33060:3306"
  adminer:
    image: adminer:latest
    networks:
      - backend
    ports:
      - 8800:8080