version: '3.3'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}
  default:
    external: 
      name: database

services:
  nginx:
    image: laravel/nginx:latest
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    ports:
      - "8000:80"
    networks:
      backend:
        aliases:
          - ${APP_HOST}
    restart: always

  php-fpm:
    image: laravel/php:latest
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    networks:
      - backend
      - default
    restart: always